In [2]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
a.size

8

In [3]:
a.ndim

1

In [4]:
a.shape

(8,)

In [8]:
u=np.array([1,2])
v=np.array([3,4])

In [9]:
u+v

array([4, 6])

In [10]:
u*v

array([3, 8])

In [11]:
u*2

array([2, 4])

In [12]:
u-v

array([-2, -2])

In [13]:
v-u

array([2, 2])

In [14]:
np.dot(u,v)

np.int64(11)

In [15]:
a.mean()

np.float64(4.5)

In [18]:
a.max()

np.int64(8)

In [ ]:
a.sort()

In [20]:
a.std()

np.float64(2.29128784747792)

In [19]:
pi=np.pi
pi

3.141592653589793

In [21]:
np.sin(2*pi)

np.float64(-2.4492935982947064e-16)

In [22]:
a=np.array([[1,2,3], [ 4,5,6], [ 7,8,9]])
a.size

9

In [24]:
a.ndim

2

In [25]:
a.shape

(3, 3)

In [26]:
a[2]

array([7, 8, 9])

In [27]:
a[2][0]

np.int64(7)

In [29]:
a[0:2,2]

array([3, 6])

In [30]:
b=np.array([[1,2,3], [ 4,5,6], [ 7,8,9]])

In [31]:
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [32]:
np.dot(a, b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [33]:
a*b

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [34]:
a+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [35]:
# Element-wise operations
arr = np.array([1, 2, 3, 4])
print(arr + 10)  # Adds 10 to each element: [11, 12, 13, 14]

[11 12 13 14]


In [37]:
# Reshaping the array
arr2d = np.arange(6).reshape(2, 3)
print(arr2d)

[[0 1 2]
 [3 4 5]]
